org:
  junjie:
    code:
      image:
        length: 3
        #需要图形验证码拦截的url，使用逗号分隔
        url: /user,/user/*
    browser:
      #配置后将使用自定义的登录页
      #      loginPage: /demo-signIn.html
      loginType: JSON
#      授权登录后如果没有注册用户，且没有实现ConnectionSignUp则会默认跳转到这里,如果ConnectionSignUp有实现类则不会跳转
      signUpUrl: /demo-signUp.html
    social:
#      qq授权登录处理接口,在自定义的JunjieSpringSocialConfiger#postProcess中进行添加
      filterProcessesUrl: /qqLogin
      qq:
#        appId: 101386962
        appId: 101878187
        appSecret: 206a7ec62e0fc929eb00b5fc9f3d7415
#        appSecret: 2a0f820407df400b84a854d054be8b6a
        providerId: callback.do
      weixin:
        appId: wx159cd6c2baa16855
        appSecret: 49c5f28a4839ec0fe6d8e721eaea9871
#数据库连接配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security_demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
server:
  port: 80